src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Final__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the score is final.</description>
        <label>Final</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <formula>IF(ISBLANK(Winner__c), 0.0, IF(Winner__c == &apos;PUSH&apos;, 0.5, 1.0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Points</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>GAME-{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <description>A junction object that links to the player&apos;s User account</description>
    <fields>
        <fullName>Nickname__c</fullName>
        <description>Player nickname</description>
        <externalId>true</externalId>
        <inlineHelpText>Player nickname</inlineHelpText>
        <label>Nickname</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Points_Available__c</fullName>
        <label>Total Points Available</label>
        <summarizedField>Weekly_Result__c.Total_Points_Available__c</summarizedField>
        <summaryForeignKey>Weekly_Result__c.Player__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Points__c</fullName>
        <label>Total Points</label>
        <summarizedField>Weekly_Result__c.Total_Points__c</summarizedField>
        <summaryForeignKey>Weekly_Result__c.Player__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The player&apos;s User account</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Win_Percentage__c</fullName>
        <formula>IF(Total_Points_Available__c == 0, 0, Total_Points__c / Total_Points_Available__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Win Percentage</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Weekly_Result__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Weekly Results</relationshipLabel>
        <relationshipName>Weekly_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Points_Available__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Points Available</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Points</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Win_Percentage__c</fullName>
        <formula>IF(Total_Points_Available__c == 0, 0,  Total_Points__c  /  Total_Points_Available__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Win Percentage</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Weekly Result</label>
    <nameField>
        <displayFormat>WR-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ResultsService.cls
public with sharing class ResultsService {

    public class Results {
        @AuraEnabled public Decimal pointsAvailable { get; set; }
        @AuraEnabled public List<ResultWrapper> resultRows { get; set; }
    }

    public class ResultWrapper {
        @AuraEnabled public String nickname { get; set; }
        @AuraEnabled public Decimal pointsScored { get; set; }
        @AuraEnabled public Decimal winPercentage { get; set; }

        public ResultWrapper(String nickname, Decimal pointsScored, Decimal winPercentage) {
            this.nickname = nickname;
            this.pointsScored = pointsScored;
            this.winPercentage = winPercentage;
        }
    }

    @AuraEnabled(cacheable=true)
    public static Results getWeeklyResults(String week) {
        AggregateResult[] ar = [
            SELECT SUM(Points__c) pointsAvailable
            FROM Game__c
            WHERE Week__c = :week AND Final__c = true
        ];
        Decimal pointsAvailable = (Decimal) ar[0].get('pointsAvailable');

        List<Weekly_Result__c> wrList = [
            SELECT Id, Name, Week__c, Player__r.Nickname__c,
                Total_Points__c, Total_Points_Available__c, Win_Percentage__c
            FROM Weekly_Result__c
            WHERE Week__c = :week
            ORDER BY Total_Points__c DESC
        ];

        Results r = new Results();
        r.pointsAvailable = pointsAvailable;
        r.resultRows = new List<ResultWrapper>();
        for (Weekly_Result__c wr : wrList) {
            r.resultRows.add(new ResultWrapper(
                wr.Player__r.Nickname__c,
                wr.Total_Points__c,
                wr.Win_Percentage__c
            ));
        }
        return r;
    }

    @AuraEnabled(cacheable=true)
    public static Results getSeasonalResults() {
        AggregateResult[] ar = [
            SELECT SUM(Points__c) pointsAvailable
            FROM Game__c
            WHERE Final__c = true
        ];
        Decimal pointsAvailable = (Decimal) ar[0].get('pointsAvailable');

        List<Player__c> pList = [
            SELECT Id, Nickname__c, Total_Points__c,
                Total_Points_Available__c, Win_Percentage__c
            FROM Player__c
            WHERE User__r.IsActive = true
            ORDER BY Total_Points__c DESC
        ];

        Results r = new Results();
        r.pointsAvailable = pointsAvailable;
        r.resultRows = new List<ResultWrapper>();
        for (Player__c p : pList) {
            r.resultRows.add(new ResultWrapper(
                p.Nickname__c,
                p.Total_Points__c,
                p.Win_Percentage__c
            ));
        }
        return r;
    }
}