src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Final__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the score is final.</description>
        <label>Final</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spread__c</fullName>
        <description>Point spread with respect to home team. Negative number indicates home team is favorite. Positive number indicates visiting team is favorite. Zero indicates a pick&apos;em game.</description>
        <label>Spread</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Scheduled starting time/date of the game.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Visiting_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visiting Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games (Visiting Team)</relationshipLabel>
        <relationshipName>Games1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>GAME-{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <description>A junction object that links to the player&apos;s User account</description>
    <fields>
        <fullName>Nickname__c</fullName>
        <description>Player nickname</description>
        <externalId>true</externalId>
        <inlineHelpText>Player nickname</inlineHelpText>
        <label>Nickname</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Settings</label>
        <referenceTo>Settings__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The player&apos;s User account</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Settings__c.object
<CustomObject>
    <description>PoolManager settings</description>
    <fields>
        <fullName>CurrentWeek__c</fullName>
        <label>Current Week</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EntryFee__c</fullName>
        <description>The pool entry fee</description>
        <inlineHelpText>The pool entry fee</inlineHelpText>
        <label>Entry Fee</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MaxGames__c</fullName>
        <description>The maximum number of games that will ever be played in a week.</description>
        <inlineHelpText>The maximum number of games that will ever be played in a week.</inlineHelpText>
        <label>Maximum Number of Games</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfWeeks__c</fullName>
        <description>Number of weeks in the pool &quot;season&quot;.</description>
        <inlineHelpText>Number of weeks in the pool &quot;season&quot;.</inlineHelpText>
        <label>Number of Weeks</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UsernameSuffix__c</fullName>
        <description>The string that is used as the default suffix for new usernames. For example nflpool.dev. This will appear in the &quot;Username&quot; field when creating new players.</description>
        <inlineHelpText>The string that is used as the default suffix for new usernames. For example nflpool.dev. This will appear in the &quot;Username&quot; field when creating new players.</inlineHelpText>
        <label>Username Suffix</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Settings</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Short_Name__c</fullName>
        <externalId>true</externalId>
        <label>Short Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UnitTestUtils.cls
@IsTest
public with sharing class UnitTestUtils {
	
	public static Settings__c createTestSettings() {
		Settings__c s = new Settings__c(
			Name = 'Pool Settings',
			CurrentWeek__c = 1,
			EntryFee__c = 150.00,
			MaxGames__c = 16,
			NumberOfWeeks__c = 17,
			UsernameSuffix__c = 'nflpool.com'
		);
		insert s;
		return s;
	}
	
	public static User createTestUser() {
		Profile p = [select id from profile where name='Player'];
		User u = new User(
			Alias = 'tplayer', 
			EmailEncodingKey = 'UTF-8',
			FirstName = 'Test', 
			LastName = 'Player',
			Email = 'tuser@test.com',
			Phone = '(222) 333-4444',
			Street = '123 Main Street', 
			City = 'Stamford', 
			State = 'CT', 
			PostalCode = '06905',
			LanguageLocaleKey='en_US', 
			LocaleSidKey = 'en_US', 
			ProfileId = p.Id,
			TimeZoneSidKey = 'America/New_York', 
			Username='test.player@nflpool.com',
			CommunityNickname='tplayer123'
		);
		return u;
	}
	
	public static Player__c createTestPlayer(User u, String nickname) {
		Player__c p = new Player__c(
			Name = u.FirstName + ' ' + u.LastName,
			Nickname__c = nickname,
			Phone__c = u.Phone,
			Settings__c = [SELECT Id FROM Settings__c].Id,
			User__c = u.Id
		);
		insert p;
		return p;
	}
	
	public static List<Team__c> createTestTeams() {
		List<Team__c> teamList = (List<Team__c>) System.Test.loadData(Team__c.SObjectType, 'testTeams');
		return teamList;
	}
	
	// Creates the specified number of games for the current week. Games are generated in order by team list
	public static List<Game__c> createTestGames(Settings__c settings, Integer numGames) {
		List<Team__c> teamList = [SELECT Id, Name, Short_Name__c FROM Team__c ORDER BY Short_Name__c];
		List<Game__c> gameList = new List<Game__c>();
		for (Integer i = 0; i < numGames; i++) {
			Game__c game = new Game__c(
				Week__c = String.valueOf(settings.CurrentWeek__c),
				Home_Team__c = teamList[i].Id,
				Visiting_Team__c = teamList[i+1].Id,
				Final__c = false,
				Start_Time__c = DateTime.now().addDays(1),
				Spread__c = Double.valueOf(i)
			);
			gameList.add(game);
		}
		insert gameList;
		return gameList;
	}
}