src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Home_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Scheduled starting time/date of the game.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Visiting_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visiting Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games (Visiting Team)</relationshipLabel>
        <relationshipName>Games1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>GAME-{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <description>A junction object that links to the player&apos;s User account</description>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Selection__c.object
<CustomObject>
    <description>Represents a player&apos;s selection for a given game</description>
    <fields>
        <fullName>Game__c</fullName>
        <description>The selected game</description>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Selections</relationshipLabel>
        <relationshipName>Selections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <description>The player that made this selection</description>
        <inlineHelpText>The player that made this selection</inlineHelpText>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Selections</relationshipLabel>
        <relationshipName>Selections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The selected team</description>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Selections</relationshipLabel>
        <relationshipName>Selections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Selection</label>
    <nameField>
        <displayFormat>SEL-{00000}</displayFormat>
        <label>Selection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GameSelection.cls
public class GameSelection {

	public Integer gameNumber { get; set; }
    public Game__c game { get; set; }
    public Selection__c selection { get; set; }
    public String playerId { get; set; }
    
    public Boolean isLocked { 
    	get {
    		Game__c current = [select start_time__c from game__c where id=:game.id limit 1];
    		return (Datetime.now() > current.start_time__c);
    	}
    }
    
    public Boolean hSelect { 
    	get {
    		if (hSelect == null) {
    			hSelect = false;
    		}
    		return hSelect;
    	}
    	set; 
    }
    
    public Boolean vSelect { 
    	get {
    		if (vSelect == null) {
    			vSelect = false;
    		}
    		return vSelect;
    	}
    	set; 
    }
        
    public Boolean isDirty { 
    	get {
   			isDirty = false;
    		if (selection != null) {
	  			isDirty = !(selectedTeam == selection.Team__c);
    		} else {
    			if (selectedTeam != null) {
    				isDirty = true;
    			}
    		}
    		return isDirty;
    	}
    	set;
    }
    
    public String selectedTeam { 
    	get {
	        if (true == hSelect) {
	            return game.Home_Team__c;
	        } else if (true == vSelect) {
	            return game.Visiting_Team__c;
	        } else {
	        	return null;
	        }
    	}
    }
 
    public GameSelection(Integer gameNumber, String playerId, Game__c game, Selection__c selection) {   
        this.gameNumber = gameNumber;
        this.playerId = playerId;
        this.game = game;
        this.selection = selection;
	    if (selection != null) {
    		// Set the hSelect or vSelect flags
    		if (selection.team__c == game.home_team__c) {
    			this.hSelect = true;
    			this.vSelect = false;
    		} else if (selection.team__c == game.visiting_team__c) {
    			this.vSelect = true;
    			this.hselect = false;
    		}
       	} else {
       		this.hSelect = false;
       		this.vSelect = false;
	    }
    }
    
    /**
     * Saves this game selection. By contract, this method should only be called when
     * there are unsaved changes, i.e. the GameSelection "is dirty".
     */
    public void save(Boolean isAdmin) {
        // Only try to save the game if it is not locked or if we are the admin        
        if (!(isLocked) || (isAdmin)) {
		    
            // First, create a new Selection object if necessary
            if (selection == null) {
            	try {
	            	// See if there's an existing selection
	            	Selection__c existingSelection = [Select s.Id, s.Name, s.Game__c, s.Player__c, s.Team__c 
	            		From Selection__c s Where s.Game__c = :game.Id and s.Player__c = :playerId limit 1];
	            		
	            	// A selection, we'll just update it
	            	selection = existingSelection;
	            		
            	} catch (QueryException qe) {
            		 
            		// No selection exists yet, so create one 
	                selection = new Selection__c();
					selection.game__c = game.Id;
					selection.player__c = playerId;                	                
            	}
            }            
     
            // Set the selected team based on which checkbox is selected
            selection.Team__c = selectedTeam;
            upsert selection;
            
        // Can't save the game because it is locked    
        } else {
            throw new SaveException('Unable to save selection because the game is locked');
        }
    }
}