src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Home_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spread__c</fullName>
        <description>Point spread with respect to home team. Negative number indicates home team is favorite. Positive number indicates visiting team is favorite. Zero indicates a pick&apos;em game.</description>
        <label>Spread</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Scheduled starting time/date of the game.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Visiting_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visiting Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games (Visiting Team)</relationshipLabel>
        <relationshipName>Games1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>GAME-{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <description>A junction object that links to the player&apos;s User account</description>
    <fields>
        <fullName>Nickname__c</fullName>
        <description>Player nickname</description>
        <externalId>true</externalId>
        <inlineHelpText>Player nickname</inlineHelpText>
        <label>Nickname</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Settings</label>
        <referenceTo>Settings__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The player&apos;s User account</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Selection__c.object
<CustomObject>
    <description>Represents a player&apos;s selection for a given game</description>
    <fields>
        <fullName>Game__c</fullName>
        <description>The selected game</description>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Selections</relationshipLabel>
        <relationshipName>Selections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <description>The player that made this selection</description>
        <inlineHelpText>The player that made this selection</inlineHelpText>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Selections</relationshipLabel>
        <relationshipName>Selections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The selected team</description>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Selections</relationshipLabel>
        <relationshipName>Selections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Selection</label>
    <nameField>
        <displayFormat>SEL-{00000}</displayFormat>
        <label>Selection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Settings__c.object
<CustomObject>
    <description>PoolManager settings</description>
    <label>Settings</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Short_Name__c</fullName>
        <externalId>true</externalId>
        <label>Short Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_SelectionService.cls
@isTest
private class Test_SelectionService {

    static testMethod void testGetSelectionsForPlayerWeek() {
        Settings__c s = UnitTestUtils.createTestSettings();
        UnitTestUtils.createTestTeams();
        List<Game__c> games = UnitTestUtils.createTestGames(s, 3);
        Player__c player = new Player__c(Name = 'Test Player', Nickname__c = 'TestP', Settings__c = s.Id);
        insert player;

        // Create some selections
        List<Selection__c> selections = new List<Selection__c>();
        selections.add(new Selection__c(Game__c = games[0].Id, Player__c = player.Id, Team__c = games[0].Home_Team__c));
        selections.add(new Selection__c(Game__c = games[1].Id, Player__c = player.Id, Team__c = games[1].Visiting_Team__c));
        insert selections;

        Test.startTest();
        SelectionService.SelectionsResult result = SelectionService.getSelectionsForPlayerWeek(player.Id, '1');
        Test.stopTest();

        System.assertEquals(3, result.numGames);
        System.assertEquals(2, result.numSelections);
        System.assertEquals(3, result.gameSelections.size());
        System.assertEquals(1, result.gameSelections[0].gameNumber);
        // Games have start time tomorrow, so not locked
        System.assertEquals(false, result.gameSelections[0].isLocked);
        System.assertNotEquals(null, result.gameSelections[0].selectedTeamId);
        System.assertEquals(null, result.gameSelections[2].selectedTeamId);
    }

    static testMethod void testGetSelectionsNoPlayer() {
        Settings__c s = UnitTestUtils.createTestSettings();
        UnitTestUtils.createTestTeams();
        UnitTestUtils.createTestGames(s, 2);

        Test.startTest();
        SelectionService.SelectionsResult result = SelectionService.getSelectionsForPlayerWeek(null, '1');
        Test.stopTest();

        System.assertEquals(2, result.numGames);
        System.assertEquals(0, result.numSelections);
        System.assertEquals(0, result.totalPoints);
    }

    static testMethod void testSaveSelection() {
        Settings__c s = UnitTestUtils.createTestSettings();
        UnitTestUtils.createTestTeams();
        List<Game__c> games = UnitTestUtils.createTestGames(s, 1);
        Player__c player = new Player__c(Name = 'Test Player', Nickname__c = 'TestP', Settings__c = s.Id);
        insert player;

        Test.startTest();
        SelectionService.saveSelection(games[0].Id, player.Id, games[0].Home_Team__c, false);
        Test.stopTest();

        List<Selection__c> saved = [SELECT Team__c FROM Selection__c WHERE Game__c = :games[0].Id AND Player__c = :player.Id];
        System.assertEquals(1, saved.size());
        System.assertEquals(games[0].Home_Team__c, saved[0].Team__c);
    }

    static testMethod void testSaveSelectionUpdate() {
        Settings__c s = UnitTestUtils.createTestSettings();
        UnitTestUtils.createTestTeams();
        List<Game__c> games = UnitTestUtils.createTestGames(s, 1);
        Player__c player = new Player__c(Name = 'Test Player', Nickname__c = 'TestP', Settings__c = s.Id);
        insert player;

        // Create initial selection
        insert new Selection__c(Game__c = games[0].Id, Player__c = player.Id, Team__c = games[0].Home_Team__c);

        Test.startTest();
        // Change selection to visiting team
        SelectionService.saveSelection(games[0].Id, player.Id, games[0].Visiting_Team__c, false);
        Test.stopTest();

        List<Selection__c> saved = [SELECT Team__c FROM Selection__c WHERE Game__c = :games[0].Id AND Player__c = :player.Id];
        System.assertEquals(1, saved.size());
        System.assertEquals(games[0].Visiting_Team__c, saved[0].Team__c);
    }

    static testMethod void testSaveSelectionDeselect() {
        Settings__c s = UnitTestUtils.createTestSettings();
        UnitTestUtils.createTestTeams();
        List<Game__c> games = UnitTestUtils.createTestGames(s, 1);
        Player__c player = new Player__c(Name = 'Test Player', Nickname__c = 'TestP', Settings__c = s.Id);
        insert player;

        // Create initial selection
        insert new Selection__c(Game__c = games[0].Id, Player__c = player.Id, Team__c = games[0].Home_Team__c);

        Test.startTest();
        // Deselecting (null team) should delete the underlying Selection__c record
        SelectionService.saveSelection(games[0].Id, player.Id, null, false);
        Test.stopTest();

        List<Selection__c> saved = [SELECT Id FROM Selection__c WHERE Game__c = :games[0].Id AND Player__c = :player.Id];
        System.assertEquals(0, saved.size());
    }

    static testMethod void testSaveSelectionDeselectNoExisting() {
        Settings__c s = UnitTestUtils.createTestSettings();
        UnitTestUtils.createTestTeams();
        List<Game__c> games = UnitTestUtils.createTestGames(s, 1);
        Player__c player = new Player__c(Name = 'Test Player', Nickname__c = 'TestP', Settings__c = s.Id);
        insert player;

        Test.startTest();
        // Deselecting when there was never a selection should be a no-op, not an error
        SelectionService.saveSelection(games[0].Id, player.Id, null, false);
        Test.stopTest();

        List<Selection__c> saved = [SELECT Id FROM Selection__c WHERE Game__c = :games[0].Id AND Player__c = :player.Id];
        System.assertEquals(0, saved.size());
    }

    static testMethod void testSaveSelectionLockedGame() {
        Settings__c s = UnitTestUtils.createTestSettings();
        UnitTestUtils.createTestTeams();
        List<Team__c> teams = [SELECT Id FROM Team__c ORDER BY Short_Name__c LIMIT 2];
        Game__c lockedGame = new Game__c(
            Week__c = '1',
            Home_Team__c = teams[0].Id,
            Visiting_Team__c = teams[1].Id,
            Start_Time__c = DateTime.now().addDays(-1),
            Spread__c = 3.0
        );
        insert lockedGame;
        Player__c player = new Player__c(Name = 'Test Player', Nickname__c = 'TestP', Settings__c = s.Id);
        insert player;

        Test.startTest();
        try {
            SelectionService.saveSelection(lockedGame.Id, player.Id, teams[0].Id, false);
            System.assert(false, 'Expected AuraHandledException');
        } catch (AuraHandledException e) {
            System.assert(e.getMessage().contains('locked'));
        }
        Test.stopTest();
    }

    static testMethod void testSaveSelectionLockedGameAsAdmin() {
        Settings__c s = UnitTestUtils.createTestSettings();
        UnitTestUtils.createTestTeams();
        List<Team__c> teams = [SELECT Id FROM Team__c ORDER BY Short_Name__c LIMIT 2];
        Game__c lockedGame = new Game__c(
            Week__c = '1',
            Home_Team__c = teams[0].Id,
            Visiting_Team__c = teams[1].Id,
            Start_Time__c = DateTime.now().addDays(-1),
            Spread__c = 3.0
        );
        insert lockedGame;
        Player__c player = new Player__c(Name = 'Test Player', Nickname__c = 'TestP', Settings__c = s.Id);
        insert player;

        Test.startTest();
        // Admin can save even when locked
        SelectionService.saveSelection(lockedGame.Id, player.Id, teams[0].Id, true);
        Test.stopTest();

        List<Selection__c> saved = [SELECT Team__c FROM Selection__c WHERE Game__c = :lockedGame.Id AND Player__c = :player.Id];
        System.assertEquals(1, saved.size());
    }

    static testMethod void testGetActivePlayers() {
        Settings__c s = UnitTestUtils.createTestSettings();
        User playerUser = UnitTestUtils.createTestUser();
        User adminUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(adminUser) {
            insert playerUser;
            UnitTestUtils.createTestPlayer(playerUser, 'TestPlayer');
        }

        Test.startTest();
        List<Map<String, String>> players = SelectionService.getActivePlayers();
        Test.stopTest();

        System.assert(players.size() > 0);
        Boolean found = false;
        for (Map<String, String> p : players) {
            System.assertNotEquals(null, p.get('value'));
            System.assertNotEquals(null, p.get('label'));
            if (p.get('label').contains('tplayer123')) {
                found = true;
            }
        }
        System.assert(found, 'Test player should appear in active players list');
    }

    static testMethod void testGetCurrentPlayerIdForUser() {
        Settings__c s = UnitTestUtils.createTestSettings();
        User adminUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Player__c player = new Player__c(Name = 'Admin Player', Nickname__c = 'AdminP', Settings__c = s.Id, User__c = adminUser.Id);
        insert player;

        Test.startTest();
        String playerId = SelectionService.getCurrentPlayerIdForUser();
        Test.stopTest();

        System.assertEquals(player.Id, playerId);
    }

    static testMethod void testGetCurrentPlayerIdForUserNoPlayer() {
        UnitTestUtils.createTestSettings();

        Test.startTest();
        String playerId = SelectionService.getCurrentPlayerIdForUser();
        Test.stopTest();

        System.assertEquals(null, playerId);
    }
}