src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Home_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Scheduled starting time/date of the game.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Visiting_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visiting Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games (Visiting Team)</relationshipLabel>
        <relationshipName>Games1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>GAME-{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <description>A junction object that links to the player&apos;s User account</description>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_GameSelection.cls
@isTest
private class Test_GameSelection {
    
    static testMethod void testGameSelection() {
    	UnitTestUtils.createTestSettings();
    	UnitTestUtils.createTestTeams();
    	User testUser = UnitTestUtils.createTestUser();
    	User adminUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
    	System.runAs(adminUser) {
    		insert testUser;
    		Player__c testPlayer = UnitTestUtils.createTestPlayer(testUser, 'Player');
	    	List<Team__c> teams = [SELECT Id, Name FROM Team__c ORDER BY Name ASC];
	    	Team__c home = teams.get(0);
	    	Team__c visitor = teams.get(1);
	    	Game__c game = new Game__c();
	    	game.week__c = '1';
	    	game.home_team__c = home.id;
	    	game.visiting_team__c = visitor.id;
	    	game.start_time__c = Datetime.now().addMinutes(-1);
	    	insert game;
	    	GameSelection gs = new GameSelection(1, testPlayer.id, game, null); 
			System.assertEquals(game.home_team__c, gs.game.home_team__c);    	
			System.assertEquals(game.visiting_team__c, gs.game.visiting_team__c);
			System.assert(true == gs.isLocked);
			System.assert(false == gs.isDirty);
			gs.hSelect = true;
			System.assert(true == gs.isDirty);
			System.assertEquals(home.id, gs.selectedTeam);
			System.debug('home:' + home);
			System.debug('gs:' + gs);
			System.debug('selectedteam: ' + gs.selectedTeam);
			try {
				gs.save(false);
				System.assert(false);
			} catch (SaveException ex) {
				System.assert(true);
			}
			try {
				gs.save(true);
				System.assert(true);
			} catch (SaveException ex) {
				System.assert(false);
			}
			System.assert(gs.selection != null);
			System.assertEquals(home.id, gs.selection.team__c);
			System.assertEquals(game.id, gs.selection.game__c);
			System.assertEquals(testPlayer.id, gs.selection.player__c); 
			
			gs.hSelect = false;
			gs.vSelect = true;
			gs.save(true);
			System.assertEquals(visitor.id, gs.selection.team__c);	
			System.assert(false == gs.isDirty);	
    	}
    }

    static testMethod void testNewGameSelection() {
    	UnitTestUtils.createTestSettings();
    	UnitTestUtils.createTestTeams();
    	User testUser = UnitTestUtils.createTestUser();
    	User adminUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
    	System.runAs(adminUser) {
    		Player__c p = UnitTestUtils.createTestPlayer(testUser, 'Player');
	    	List<Team__c> teams =[SELECT Id, Name FROM Team__c ORDER BY Name ASC];
	    	Team__c home = teams.get(0);
	    	Team__c visitor = teams.get(1);
	    	Game__c game = new Game__c();
	    	game.week__c = '1';
	    	game.home_team__c = home.id;
	    	game.visiting_team__c = visitor.id;
	    	game.start_time__c = Datetime.now().addMinutes(-1);
	    	insert game;
	    	New_GameSelection gs = new New_GameSelection(1, p.id, game, null); 
			System.assertEquals(game.home_team__c, gs.game.home_team__c);    	
			System.assertEquals(game.visiting_team__c, gs.game.visiting_team__c);
			System.assert(true == gs.isLocked);
			System.assert(false == gs.isDirty);
			gs.hSelect = true;
			System.assert(true == gs.isDirty);
			System.assertEquals(home.id, gs.selectedTeam);
			try {
				gs.save(false);
				System.assert(false);
			} catch (SaveException ex) {
				System.assert(true);
			}
			try {
				gs.save(true);
				System.assert(true);
			} catch (SaveException ex) {
				System.assert(false);
			}
			System.assert(gs.selection != null);
			System.assertEquals(home.id, gs.selection.team__c);
			System.assertEquals(game.id, gs.selection.game__c);
			System.assertEquals(p.id, gs.selection.player__c); 
			
			gs.hSelect = false;
			gs.vSelect = true;
			gs.save(true);
			System.assertEquals(visitor.id, gs.selection.team__c);	
			System.assert(false == gs.isDirty);
    	}	
    }
}