src/objects/Player__c.object
<CustomObject>
    <description>A junction object that links to the player&apos;s User account</description>
    <fields>
        <fullName>Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Settings</label>
        <referenceTo>Settings__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Settings__c.object
<CustomObject>
    <description>PoolManager settings</description>
    <fields>
        <fullName>CurrentWeek__c</fullName>
        <label>Current Week</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Settings</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_SelectionController.cls
@isTest
private class Test_SelectionController {
	static testMethod void testSelectionController() {
		Settings__c s = UnitTestUtils.createTestSettings();
		UnitTestUtils.createTestTeams();
		UnitTestUtils.createTestGames(s, 16);
		User playerUser = UnitTestUtils.createTestUser();
		User adminUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		System.runAs(adminUser) {
			// Get a player
			insert playerUser;
			Player__c player = UnitTestUtils.createTestPlayer(playerUser, 'Player');
			PageReference printableSelectionsPage = Page.PrintableSelections;
			System.Test.setCurrentPage(printableSelectionsPage);
			SelectionController con = new SelectionController();
			System.assert(con.isadmin);
			System.assertEquals(s.currentweek__c, Integer.valueOf(con.weekNumber));

			// Simulate selection of a player
			con.selectedPlayer = player.id;
			System.assertEquals(playerUser.CommunityNickname, con.playerName);
			con.refreshGameSelections(con.weekNumber, con.selectedPlayer);
			System.assertEquals(16, con.gameSelections.size());

			GameSelection gs = con.gameSelections.get(0);
			System.assertEquals(1, gs.gameNumber);
		}
	}
}