src/objects/Player__c.object
<CustomObject>
    <description>A junction object that links to the player&apos;s User account</description>
    <fields>
        <fullName>BalanceDueFormula__c</fullName>
        <formula>IF(  User__r.IsActive , Settings__r.EntryFee__c - TotalPaymentsRollup__c, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalPaymentsRollup__c</fullName>
        <label>Total Payments</label>
        <summarizedField>PlayerPayment__c.Amount__c</summarizedField>
        <summaryForeignKey>PlayerPayment__c.Player__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlayerPayment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Payment amount</description>
        <inlineHelpText>Payment amount</inlineHelpText>
        <label>Amount</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <description>The player that made this payment</description>
        <inlineHelpText>The player that made this payment</inlineHelpText>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_PlayerWrapper.cls
@isTest
private class Test_PlayerWrapper {
	
	static testMethod void testPlayerWrapper() {
		UnitTestUtils.createTestSettings();
		User testUser = UnitTestUtils.createTestUser();
		User adminUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		System.runAs(adminUser) {
			insert testUser;
			Player__c testPlayer = UnitTestUtils.createTestPlayer(testUser, 'Player');
			
			// Create a test payment    	
			PlayerPayment__c testPayment = new PlayerPayment__c();
			testPayment.amount__c = 100;
			testPayment.player__c = testPlayer.id;
			insert testPayment;
			
			PlayerWrapper wrapper = PlayerWrapper.getPlayerWrapper(testUser.id);
			System.assertEquals(testUser.id, wrapper.usr.id);
			System.assertEquals(testPlayer.id, wrapper.player.id);
			System.assert(wrapper.player.TotalPaymentsRollup__c == 100);
			System.assert(wrapper.player.BalanceDueFormula__c == 50);
			
			List<User> users = [select id from user where profile.name = 'Player'];
			List<Id> userIds = new List<Id>();
			for (User u : users) {
				userIds.add(u.id);
			}
			List<PlayerWrapper> playerWrapperList = PlayerWrapper.getPlayerWrapperList(userIds);
			System.assert(playerWrapperList.size() > 0);
		}
	}
}