src/objects/Player__c.object
<CustomObject>
    <description>A junction object that links to the player&apos;s User account</description>
    <fields>
        <fullName>BalanceDueFormula__c</fullName>
        <formula>IF(  User__r.IsActive , Settings__r.EntryFee__c - TotalPaymentsRollup__c, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Settings</label>
        <referenceTo>Settings__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPaymentsRollup__c</fullName>
        <label>Total Payments</label>
        <summarizedField>PlayerPayment__c.Amount__c</summarizedField>
        <summaryForeignKey>PlayerPayment__c.Player__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlayerPayment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Payment amount</description>
        <inlineHelpText>Payment amount</inlineHelpText>
        <label>Amount</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <description>The player that made this payment</description>
        <inlineHelpText>The player that made this payment</inlineHelpText>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Settings__c.object
<CustomObject>
    <description>PoolManager settings</description>
    <fields>
        <fullName>EntryFee__c</fullName>
        <description>The pool entry fee</description>
        <inlineHelpText>The pool entry fee</inlineHelpText>
        <label>Entry Fee</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Settings</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TriggerTests.cls
@isTest
private class TriggerTests {
	
	static testMethod void testTriggers() {
		Settings__c settings = UnitTestUtils.createTestSettings();
		User testUser = UnitTestUtils.createTestUser();
		User adminUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		System.runAs(adminUser) {
			insert testUser;
			Player__c newPlayer = UnitTestUtils.createTestPlayer(testUser, 'Player');
			Player__c updatedPlayer = [select Id, BalanceDueFormula__c, TotalPaymentsRollup__c from Player__c where Name = 'Test Player' limit 1];
			System.assert(updatedPlayer.TotalPaymentsRollup__c == 0);
			System.assert(updatedPlayer.BalanceDueFormula__c == settings.EntryFee__c);
			
			// Create a payment
			PlayerPayment__c payment1 = new PlayerPayment__c(Amount__c = 25, Player__c = updatedPlayer.Id);
			insert payment1;
			
			updatedPlayer = [select Id, BalanceDueFormula__c, TotalPaymentsRollup__c from Player__c where Name = 'Test Player' limit 1];
			System.assert(updatedPlayer.TotalPaymentsRollup__c == payment1.Amount__c);
			System.assert(updatedPlayer.BalanceDueFormula__c == (settings.EntryFee__c - updatedPlayer.TotalPaymentsRollup__c));
			
			PlayerPayment__c payment2 = new PlayerPayment__c(Amount__c = 25, Player__c = updatedPlayer.Id);
			insert payment2;
			
			updatedPlayer = [select Id, BalanceDueFormula__c, TotalPaymentsRollup__c from Player__c where Name = 'Test Player' limit 1];
			System.assert(updatedPlayer.TotalPaymentsRollup__c == (payment1.Amount__c + payment2.Amount__c));
			System.assert(updatedPlayer.BalanceDueFormula__c == (settings.EntryFee__c - updatedPlayer.TotalPaymentsRollup__c));
			
			payment2.Amount__c = 50;
			update payment2;
			
			updatedPlayer = [select Id, BalanceDueFormula__c, TotalPaymentsRollup__c from Player__c where Name = 'Test Player' limit 1];
			System.assert(updatedPlayer.TotalPaymentsRollup__c == (payment1.Amount__c + payment2.Amount__c));
			System.assert(updatedPlayer.BalanceDueFormula__c == (settings.EntryFee__c - updatedPlayer.TotalPaymentsRollup__c));
			
			delete payment2;
			updatedPlayer = [select Id, BalanceDueFormula__c, TotalPaymentsRollup__c from Player__c where Name = 'Test Player' limit 1];
			System.assert(updatedPlayer.TotalPaymentsRollup__c == payment1.Amount__c);
			System.assert(updatedPlayer.BalanceDueFormula__c == (settings.EntryFee__c - updatedPlayer.TotalPaymentsRollup__c));
		}
	}
}