src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <externalId>true</externalId>
        <label>Short Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Selector_Team.cls
public with sharing class Selector_Team extends fflib_SObjectSelector {
	public Schema.SObjectType getSObjectType() {
		return Team__c.SObjectType;
	}

	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField>{
			Team__c.Id,
			Team__c.External_ID__c,
			Team__c.Name,
			Team__c.Short_Name__c
		};
	}

	public override String getOrderBy() {
		return Team__c.Short_Name__c.getDescribe().name;
	}

	public List<Team__c> selectAll() {
		fflib_QueryFactory qf = newQueryFactory();
		return (List<Team__c>) Database.query(qf.toSOQL());
	}
}